# -*- coding:utf-8 -*-
from loginHandler import LoginHandler
from logoutHandler import LogoutHandler
from ajaxUploadHandler import AjaxUploadHandler
from uploadHandler import UploadHandler
from categoryHandler import CategoryHandler
from indexHandler import IndexHandler
from viewHandler import ViewHandler
from downloadHandler import DownloadHandler
from documentHandler import DocumentHandler
from verifycodeHandler import VerifyCodeHandler
# admin
from adminIndexHandler import AdminIndexHandler
from adminCategoryHandler import AdminCategoryHandler
from adminUserHandler import AdminUserHandler
from adminDocumentHandler import AdminDocumentHandler
from overviewHandler import OverviewHandler
from adminExitHandler import AdminExitHandler
from adminAboutHandler import AdminAboutHandler
from adminPermissionHandler import AdminPermissionHandler
